<?php 

$ROWevento = '';$ROWotrosp1='';
$ROWevento = $altaeventos->var_altaeventos();

$ROWotrosp1= array();
//$otrosproductosporcentaje = $conexion->contadorporcentaje($ROWevento,$ROWotrosp1);


$NUMERO_EVENTO = isset($ROWevento["NUMERO_EVENTO"])?$ROWevento["NUMERO_EVENTO"]:"";
$FECHA_ALTA_EVENTO = isset($ROWevento["FECHA_ALTA_EVENTO"])?$ROWevento["FECHA_ALTA_EVENTO"]:"";                                   
$STATUS_EVENTO = isset($ROWevento["STATUS_EVENTO"])?$ROWevento["STATUS_EVENTO"]:"";
$FECHA_AUTORIZACION_EVENTO = isset($ROWevento["FECHA_AUTORIZACION_EVENTO"])?$ROWevento["FECHA_AUTORIZACION_EVENTO"]:"";
$MONTOC_TOTAL_EVENTO = isset($ROWevento["MONTOC_TOTAL_EVENTO"])?$ROWevento["MONTOC_TOTAL_EVENTO"]:"";
$MONTO_TOTAL_AVION = isset($ROWevento["MONTO_TOTAL_AVION"])?$ROWevento["MONTO_TOTAL_AVION"]:"";
$PORCENTAJE_FEE = isset($ROWevento["PORCENTAJE_FEE"])?$ROWevento["PORCENTAJE_FEE"]:"";
$CANTIDAD_PORCENTAJEV = isset($ROWevento["CANTIDAD_PORCENTAJEV"])?$ROWevento["CANTIDAD_PORCENTAJEV"]:"";
$FEE_COBRADO = isset($ROWevento["FEE_COBRADO"])?$ROWevento["FEE_COBRADO"]:"";
$MONTO_TOTAL_DEL_EVENTO = isset($ROWevento["MONTO_TOTAL_DEL_EVENTO"])?$ROWevento["MONTO_TOTAL_DEL_EVENTO"]:"";
$NOMBRE_COMERCIAL_EVENTO = isset($ROWevento["NOMBRE_COMERCIAL_EVENTO"])?$ROWevento["NOMBRE_COMERCIAL_EVENTO"]:"";
$NOMBRE_FISCAL_EVENTO = isset($ROWevento["NOMBRE_FISCAL_EVENTO"])?$ROWevento["NOMBRE_FISCAL_EVENTO"]:"";
$NOMBRE_EVENTO = isset($ROWevento["NOMBRE_EVENTO"])?$ROWevento["NOMBRE_EVENTO"]:"";
$NOMBRE_CORTO_EVENTO = isset($ROWevento["NOMBRE_CORTO_EVENTO"])?$ROWevento["NOMBRE_CORTO_EVENTO"]:"";
$NOMBRE_CONTACTO_EVENTO = isset($ROWevento["NOMBRE_CONTACTO_EVENTO"])?$ROWevento["NOMBRE_CONTACTO_EVENTO"]:"";
$CELULAR_CONTACTO_1 = isset($ROWevento["CELULAR_CONTACTO_1"])?$ROWevento["CELULAR_CONTACTO_1"]:"";
$CORREO_CONTACTO_1 = isset($ROWevento["CORREO_CONTACTO_1"])?$ROWevento["CORREO_CONTACTO_1"]:"";
$AREA_CONTACTO_CLIENTE = isset($ROWevento["AREA_CONTACTO_CLIENTE"])?$ROWevento["AREA_CONTACTO_CLIENTE"]:"";
$OBSERVACIONES_1 = isset($ROWevento["OBSERVACIONES_1"])?$ROWevento["OBSERVACIONES_1"]:"";
$TIPO_DE_EVENTO = isset($ROWevento["TIPO_DE_EVENTO"])?$ROWevento["TIPO_DE_EVENTO"]:"";
$FORMATO_EVENTO = isset($ROWevento["FORMATO_EVENTO"])?$ROWevento["FORMATO_EVENTO"]:"";
$PAIS_DEL_EVENTO = isset($ROWevento["PAIS_DEL_EVENTO"])?$ROWevento["PAIS_DEL_EVENTO"]:"";
$CIUDAD_DEL_EVENTO = isset($ROWevento["CIUDAD_DEL_EVENTO"])?$ROWevento["CIUDAD_DEL_EVENTO"]:"";
$HOTEL_LUGAR = isset($ROWevento["HOTEL_LUGAR"])?$ROWevento["HOTEL_LUGAR"]:"";
$NUMERO_DE_PERSONAS = isset($ROWevento["NUMERO_DE_PERSONAS"])?$ROWevento["NUMERO_DE_PERSONAS"]:"";
$FECHA_INICIO_EVENTO = isset($ROWevento["FECHA_INICIO_EVENTO"])?$ROWevento["FECHA_INICIO_EVENTO"]:"";
$NOMBRE_COMERCIAL = isset($ROWevento["NOMBRE_COMERCIAL"])?$ROWevento["NOMBRE_COMERCIAL"]:"";
$FECHA_FINAL_EVENTO = isset($ROWevento["FECHA_FINAL_EVENTO"])?$ROWevento["FECHA_FINAL_EVENTO"]:"";//
$HORA_TERMINO_EVENTO = isset($ROWevento["HORA_TERMINO_EVENTO"])?$ROWevento["HORA_TERMINO_EVENTO"]:"";
$FECHA_LLEGADA_STAFF = isset($ROWevento["FECHA_LLEGADA_STAFF"])?$ROWevento["FECHA_LLEGADA_STAFF"]:"";
$HORA_LLEGADA_STAFF = isset($ROWevento["HORA_LLEGADA_STAFF"])?$ROWevento["HORA_LLEGADA_STAFF"]:"";
$FECHA_REGRESO_STAFF = isset($ROWevento["FECHA_REGRESO_STAFF"])?$ROWevento["FECHA_REGRESO_STAFF"]:"";
$HORA_REGRESO_STAFF = isset($ROWevento["HORA_REGRESO_STAFF"])?$ROWevento["HORA_REGRESO_STAFF"]:"";
 $MATERIAL_EQUIPO_BODEGA = isset($ROWevento["MATERIAL_EQUIPO_BODEGA"])?$ROWevento["MATERIAL_EQUIPO_BODEGA"]:"";
$FECHA_INICIO_MONTAJE = isset($ROWevento["FECHA_INICIO_MONTAJE"])?$ROWevento["FECHA_INICIO_MONTAJE"]:"";
$HORA_INICIO_MONTAJE = isset($ROWevento["HORA_INICIO_MONTAJE"])?$ROWevento["HORA_INICIO_MONTAJE"]:"";
$FECHA_DESMONTAJE = isset($ROWevento["FECHA_DESMONTAJE"])?$ROWevento["FECHA_DESMONTAJE"]:"";
$HORA_DESMONTAJE = isset($ROWevento["HORA_DESMONTAJE"])?$ROWevento["HORA_DESMONTAJE"]:"";
$LUGAR_MONTAJE = isset($ROWevento["LUGAR_MONTAJE"])?$ROWevento["LUGAR_MONTAJE"]:"";
$ARCHIVO_RELACIONADO_MONTAJE = isset($ROWevento["ARCHIVO_RELACIONADO_MONTAJE"])?$ROWevento["ARCHIVO_RELACIONADO_MONTAJE"]:"";
$SERVICIO_OTORGAR = isset($ROWevento["SERVICIO_OTORGAR"])?$ROWevento["SERVICIO_OTORGAR"]:"";
$hALTAEVENTOS = isset($ROWevento["hALTAEVENTOS"])?$ROWevento["hALTAEVENTOS"]:"";
$NOMBRE_VENDEDOR = isset($ROWevento["NOMBRE_VENDEDOR"])?$ROWevento["NOMBRE_VENDEDOR"]:"";
$NOMBRE_EJECUTIVOEVENTO = isset($ROWevento["NOMBRE_EJECUTIVOEVENTO"])?$ROWevento["NOMBRE_EJECUTIVOEVENTO"]:"";
$CIERRE_TOTAL = isset($ROWevento["CIERRE_TOTAL"])?$ROWevento["CIERRE_TOTAL"]:"";
$TOTAL_AVION_SINIVA = isset($ROWevento["TOTAL_AVION_SINIVA"])?$ROWevento["TOTAL_AVION_SINIVA"]:"";
$MONEDAS = isset($ROWevento["MONEDAS"])?$ROWevento["MONEDAS"]:"";
$NOMBRE_INGRESO = isset($ROWevento["NOMBRE_INGRESO"])?$ROWevento["NOMBRE_INGRESO"]:"";
$IPaltaeventos = isset($ROWevento["id"])?$ROWevento["id"]:""; 

$ROWevento = $altaeventos->var_altaeventosdoctos();

$ROWotrosp1= array();

$IMAGEN_EVENTO = isset($ROWevento["IMAGEN_EVENTO"])?$ROWevento["IMAGEN_EVENTO"]:"";
$LOGO_CLIENTE = isset($ROWevento["LOGO_CLIENTE"])?$ROWevento["LOGO_CLIENTE"]:"";
$SUBIR_COTIZACION_FIRMADA = isset($ROWevento["SUBIR_COTIZACION_FIRMADA"])?$ROWevento["SUBIR_COTIZACION_FIRMADA"]:"";
$SUBIR_CONTRATO_FIRMADO = isset($ROWevento["SUBIR_CONTRATO_FIRMADO"])?$ROWevento["SUBIR_CONTRATO_FIRMADO"]:"";
$SUBIR_ORDEN_COMPRA = isset($ROWevento["SUBIR_ORDEN_COMPRA"])?$ROWevento["SUBIR_ORDEN_COMPRA"]:"";
$SUBIR_COTIZACION = isset($ROWevento["SUBIR_COTIZACION"])?$ROWevento["SUBIR_COTIZACION"]:"";
$LUGAR_MONTAJE = isset($ROWevento["LUGAR_MONTAJE"])?$ROWevento["LUGAR_MONTAJE"]:"";



